# Generated by Django 2.1.5 on 2019-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0002_auto_20190107_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='urls',
            field=models.ManyToManyField(related_name='session_url', to='url_tester.URL'),
        ),
    ]
