# Generated by Django 2.1.5 on 2019-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0004_auto_20190107_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
