# Generated by Django 2.1.5 on 2019-01-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0005_url_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='url_load',
            field=models.URLField(blank=True, null=True),
        ),
    ]
