# Generated by Django 2.1.5 on 2019-01-09 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('url_tester', '0006_session_url_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionURLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Session URL',
                'verbose_name_plural': 'Sessions URL',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='session',
            name='urls',
        ),
        migrations.AddField(
            model_name='session',
            name='urls',
            field=models.ManyToManyField(related_name='session_url', through='url_tester.SessionURLS',
                                         to='url_tester.URL'),
        ),
        migrations.AddField(
            model_name='sessionurls',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_urls',
                                    to='url_tester.Session'),
        ),
        migrations.AddField(
            model_name='sessionurls',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url',
                                    to='url_tester.URL'),
        ),
    ]
