# Generated by Django 2.1.5 on 2019-01-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0008_session_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='urls',
            field=models.ManyToManyField(blank=True, null=True, related_name='session_url', through='url_tester.SessionURLS', to='url_tester.URL'),
        ),
    ]
