# Generated by Django 2.1.5 on 2019-01-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0011_auto_20190109_1131'),
    ]

    operations = [

    ]
