# Generated by Django 2.1.5 on 2019-01-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0012_auto_20190109_1156'),
    ]

    operations = [
    ]
