# Generated by Django 2.1.5 on 2019-01-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0014_auto_20190109_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionurls',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessionurls',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='session',
            name='urls',
        ),
        migrations.AddField(
            model_name='session',
            name='urls',
            field=models.ManyToManyField(related_name='session_url', to='url_tester.URL'),
        ),
        migrations.DeleteModel(
            name='SessionURLS',
        ),
    ]
