# Generated by Django 2.1.5 on 2019-01-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0015_auto_20190109_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='loaded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
