# Generated by Django 2.1.5 on 2019-01-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0017_auto_20190110_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
    ]
