# Generated by Django 2.1.5 on 2019-01-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0018_auto_20190111_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_category', to='url_tester.Category'),
            preserve_default=False,
        ),
    ]
