# Generated by Django 2.1.5 on 2019-01-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0019_session_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_category', to='url_tester.Category'),
        ),
    ]
