# Generated by Django 2.1.5 on 2019-01-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0020_auto_20190111_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
