# Generated by Django 2.1.5 on 2019-01-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0022_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session_project', to='url_tester.Project'),
            preserve_default=False,
        ),
    ]
