# Generated by Django 2.1.5 on 2019-01-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0023_session_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
