# Generated by Django 2.1.5 on 2019-01-11 09:24

from django.db import migrations
from django.utils.text import slugify


def slugify_title(apps, schema_edtior):
    session_model = apps.get_model('url_tester', 'Session')
    for session in session_model.objects.all():
        session.slug = slugify(session.title)
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0024_session_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_title),
    ]
