# Generated by Django 2.1.5 on 2019-01-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0027_auto_20190111_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Color Code'),
        ),
    ]
