# Generated by Django 2.1.5 on 2019-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0029_auto_20190111_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, help_text='Add the desired color code. You can choose one from: http://brand-colors.com/', max_length=7, null=True, verbose_name='Color Code'),
        ),
    ]
