# Generated by Django 2.1.5 on 2019-01-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0031_auto_20190111_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='loaded',
        ),
    ]
