# Generated by Django 2.1.5 on 2019-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0032_remove_session_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='test_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
