# Generated by Django 2.1.5 on 2019-01-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_tester', '0033_session_test_loaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='test_loaded',
        ),
    ]
